### ISSUE TITLE
Crash when switching wallets quickly

### ISSUE THREAD

**Issue by paolo96** [paolo96/scp-wallet-android#1]
Switching wallets rapidly in WalletsActivity sometimes causes a weird crash of a native process on Pixel 4 XL

2022-02-07 03:09:57.890 19116-19116/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG: Build fingerprint: 'google/coral/coral:12/SQ1A.220105.002/7961164:user/release-keys'
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG: Revision: 'MP1.0'
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG: ABI: 'arm64'
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG: Timestamp: 2022-02-07 03:09:57.501480991+0100
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG: Process uptime: 0s
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG: Cmdline: com.scp.wallet
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG: pid: 18593, tid: 18604, name: FinalizerDaemon  >>> com.scp.wallet <<<
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG: uid: 10457
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG: Abort message: 'Scudo ERROR: corrupted chunk header at address 0x2000072d3950490
    '
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG:     x0  0000000000000000  x1  00000000000048ac  x2  0000000000000006  x3  00000072276dae00
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG:     x4  0080808080808080  x5  0080808080808080  x6  0080808080808080  x7  8080808080808080
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG:     x8  00000000000000f0  x9  68790a6d5526797b  x10 0000000000000000  x11 ffffff80fffffbdf
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG:     x12 0000000000000001  x13 00000008cc755879  x14 0019b737bb3e2df5  x15 0000000000000010
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG:     x16 00000075260ec050  x17 00000075260c8eb0  x18 0000007226f5e000  x19 00000000000048a1
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG:     x20 00000000000048ac  x21 00000000ffffffff  x22 0000000000000000  x23 000000001649dbd8
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG:     x24 0000000000004344  x25 0000000016414670  x26 0000000000003e48  x27 b4000073339a5440
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG:     x28 00000072276dc000  x29 00000072276dae80
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG:     lr  000000752607bba0  sp  00000072276dade0  pc  000000752607bbcc  pst 0000000000000000
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG: backtrace:
2022-02-07 03:09:57.890 19116-19116/? A/DEBUG:       #00 pc 000000000004fbcc  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: ba489d4985c0cf173209da67405662f9)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #01 pc 0000000000040364  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::die()+8) (BuildId: ba489d4985c0cf173209da67405662f9)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #02 pc 0000000000040b00  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::ScopedErrorReport::~ScopedErrorReport()+32) (BuildId: ba489d4985c0cf173209da67405662f9)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #03 pc 0000000000040bc8  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::reportHeaderCorruption(void*)+60) (BuildId: ba489d4985c0cf173209da67405662f9)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #04 pc 0000000000042328  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::Allocator<scudo::AndroidConfig, &(scudo_malloc_postinit)>::deallocate(void*, scudo::Chunk::Origin, unsigned long, unsigned long)+296) (BuildId: ba489d4985c0cf173209da67405662f9)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #05 pc 0000000000202364  /system/lib64/libhwui.so (android::deletePathData(_JNIEnv*, _jobject*, long)+64) (BuildId: 54f0ca045711806fbd1a9a627de02feb)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #06 pc 00000000001c68e0  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot-framework.oat (art_jni_trampoline+96)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #07 pc 000000000223e2dc  /memfd:jit-cache (deleted) (android.util.PathParser.access$400+76)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #08 pc 000000000227a778  /memfd:jit-cache (deleted) (android.util.PathParser$PathData.finalize+104)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #09 pc 0000000002279db4  /memfd:jit-cache (deleted) (java.lang.Daemons$FinalizerDaemon.doFinalize+260)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #10 pc 000000000223e5e0  /memfd:jit-cache (deleted) (java.lang.Daemons$FinalizerDaemon.runInternal+544)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #11 pc 00000000002ce07c  /apex/com.android.art/lib64/libart.so (art_quick_osr_stub+60) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #12 pc 0000000000781394  /apex/com.android.art/lib64/libart.so (MterpMaybeDoOnStackReplacement+860) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #13 pc 00000000002ccf50  /apex/com.android.art/lib64/libart.so (MterpHelpers+240) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #14 pc 00000000000299be  /apex/com.android.art/javalib/core-libart.jar (java.lang.Daemons$FinalizerDaemon.runInternal+178)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #15 pc 00000000002c37dc  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+2292) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #16 pc 00000000002c8414  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #17 pc 00000000000296b6  /apex/com.android.art/javalib/core-libart.jar (java.lang.Daemons$Daemon.run+50)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #18 pc 00000000003df0b4  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+2460) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #19 pc 00000000002c8614  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #20 pc 00000000000eda70  /apex/com.android.art/javalib/core-oj.jar (java.lang.Thread.run+8)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #21 pc 000000000027d748  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.7449118509010352383)+644) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #22 pc 000000000027c8f0  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1176) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #23 pc 00000000002d7778  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #24 pc 00000000002cdd64  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #25 pc 0000000000317fb0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+156) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #26 pc 00000000003cc480  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+380) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #27 pc 000000000045eff0  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+992) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #28 pc 00000000000b1910  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: ba489d4985c0cf173209da67405662f9)
2022-02-07 03:09:57.891 19116-19116/? A/DEBUG:       #29 pc 00000000000513f0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: ba489d4985c0cf173209da67405662f9)

2022-02-07 03:09:57.945 682-682/? E/BpTransactionCompletedListener: Failed to transact (-32)
2022-02-07 03:09:57.966 1815-1877/? W/WindowManager: Failed to deliver inset state change to w=Window{6330e43 u0 com.scp.wallet/com.scp.wallet.activities.wallets.WalletsActivity}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:571)
        at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:687)
        at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3953)
        at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$6$InsetsStateController(InsetsStateController.java:552)
        at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda1.run(Unknown Source:2)
        at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
        at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:226)
        at com.android.server.wm.WindowAnimator.lambda$new$1$WindowAnimator(WindowAnimator.java:106)
        at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda0.doFrame(Unknown Source:2)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:775)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)

**Comment by paolo96** [comment]
Solved in 1d7aa43b5cf73343c2173bddb0c963d1557d5b19
